More fixes to support dev mode

diff --git a/entrypoint b/entrypoint
--- a/entrypoint
+++ b/entrypoint
@@ -10,41 +10,6 @@ fail() {
 	exit ${EXIT_CODE:-1}
 }
 
-urlencode() {
-	local STR="${1}"
-	local LEN=${#STR}
-	local RESULT=""
-	local POS C O
-
-	for (( POS=0 ; POS < LEN ; POS++ )); do
-		C=${STR:$POS:1}
-		case "${C}" in
-			[-_.~a-zA-Z0-9/] )	O="${C}" ;;
-			* )					printf -v O '%%%02x' "'${C}"
-		esac
-		RESULT+="${O}"
-	done
-	echo "${RESULT}"
-}
-
-JAVA="$(type -P java)" || fail "No Java found in the path"
-
-[ -v BASE_DIR ] || BASE_DIR="/app"
-[ -v DATA_DIR ] || DATA_DIR="${BASE_DIR}/data"
-[ -v INIT_DIR ] || INIT_DIR="${BASE_DIR}/init"
-
-[ -n "${DATA_DIR}" ] || fail "The DATA_DIR environment variable may not be empty"
-[ -e "${DATA_DIR}" ] || fail "The data directory at [${DATA_DIR}] does not exist"
-[ -d "${DATA_DIR}" ] || fail "The data directory path [${DATA_DIR}] is not a directory"
-[ -r "${DATA_DIR}" ] || fail "The data directory at [${DATA_DIR}] is not readable"
-[ -w "${DATA_DIR}" ] || fail "The data directory at [${DATA_DIR}] is not writable"
-[ -x "${DATA_DIR}" ] || fail "The data directory at [${DATA_DIR}] is not executable"
-DATA_DIR="$(readlink -f "${DATA_DIR}")"
-
-[ -v MAIN_CONF ] || MAIN_CONF="application.yaml"
-[ -v CONF ] || CONF="${DATA_DIR}/${MAIN_CONF}"
-
-
 [ -v SSL_DIR ] || SSL_DIR="/.ssl"
 acme-init
 
@@ -58,67 +23,9 @@ case "${DEVELOPMENT,,}" in
 	* ) DEVELOPMENT="false" ;;
 esac
 
-#
-# If our configuration is missing or empty, we render a new one
-#
-if [ ! -s "${CONF}" ] ; then
-	#
-	# TODO: Do we want to find all subdirectories within and index those here?
-	#
-	# We add the empty string to indicate the directory itself
-	LOCATIONS=("" "labels" "ldap" "lookups" "rules")
-	SEARCH_LOCATIONS=""
-	for L in "${LOCATIONS[@]}" ; do
-		# If we need a leading comma, add it
-		[ -n "${SEARCH_LOCATIONS}" ] && SEARCH_LOCATIONS+=","
-		LOCATION="${DATA_DIR}"
-		[ -n "${L}" ] && LOCATION="${DATA_DIR}/${L}"
-		LOCATION="$(urlencode "${LOCATION}")"
-		SEARCH_LOCATIONS="${SEARCH_LOCATIONS}file://${LOCATION}"
-	done
-	[ -v ACTIVEMQ_URL ] || ACTIVEMQ_URL="tcp://messaging:61616"
-	KEYSTORE_PASSWORD="$(<"${SSL_DIR}/keystore.pass")"
-	cat > "${CONF}" <<- EOF
-	server
-	  port: "9999"
-	spring.profiles.active: native
-	spring.cloud.config.server.native.searchLocations: "${SEARCH_LOCATIONS}"
-	spring.jms.pub-sub-domain: "true"
-	properties.folder.path: "${DATA_DIR}"
-	branding.files.folder.path: "${DATA_DIR}/branding"
-	logging.file: /dev/stdout
-	logging.level.com.armedia.acm.configserver: debug
-	logging.level.org.springframework.cloud.config: debug
-	jms.message.buffer.window: "1"
-	spring.activemq.broker-url: "${ACTIVEMQ_URL}"
-	acm.activemq.broker-url: "${ACTIVEMQ_URL}"
-	acm.activemq.default-destination: configuration.changed
-	acm.activemq.labels-destination: labels.changed
-	acm.activemq.ldap-destination: ldap.changed
-	acm.activemq.lookups-destination: lookups.changed
-	acm.activemq.rules-destination: rules.changed
-	acm.activemq.timeout: "10"
-	arkcase.languages: "-de,-en,-en-in,-es,-fr,-hi,-ja,-pt,-ru,-zh-cn,-zh-tw"
-	logging.pattern.file: "%d{yyyy-MM-dd HH:mm:ss,SSS} [%thread] %-5level %logger.%M - %msg%n"
-	java.io.tmpdir: "${TEMP_DIR}"
-	EOF
-fi
-CONF="$(readlink -f "${CONF}")"
+CLOUDCONFIG="$(type -P cloudconfig)" || fail "The cloudconfig executable was not found in the path"
 
-#
-# Make sure the configuration file gets URL-encoded
-#
-CONF="$(urlencode "${CONF}")"
-
-#
-# Execute it!
-#
-[ ${#} -lt 1 ] && set -- --spring.config.location="file://${CONF}"
-
-[ -v JAVA_OPTS ] || JAVA_OPTS=""
-JAVA_OPTS+=" -Dserver.ssl.key-alias=acme -Dserver.ssl.key-store=${SSL_DIR}/keystore.pkcs12 -Dserver.ssl.key-store-password=$(<"${SSL_DIR}"/keystore.pass)"
-
-CMD=("${JAVA}" ${JAVA_OPTS} -jar "${EXE_JAR}" "${@}")
+CMD=("${CLOUDCONFIG}" "${@}")
 
 say "Launching as: ${CMD[@]@Q}"
 
